version: "3"
services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mynetwork

    command: python AInstructor/manage.py runserver 0.0.0.0:8000

  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - django
    networks:
      - mynetwork

    command: npm run start

networks:
  mynetwork:
    driver: bridge
