# Generated by Django 4.2.1 on 2023-05-30 14:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('profil_picture', models.ImageField(max_length=254, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('is_prof', models.BooleanField(default='False')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('last_connexion', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
