# Generated by Django 4.2.1 on 2023-05-30 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_picture',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
