# Generated by Django 4.2.2 on 2023-06-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
