# Generated by Django 4.2.2 on 2023-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jwt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='jwt_access',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jwt_refresh',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
