# Generated by Django 4.1.5 on 2023-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='helloo', max_length=20),
            preserve_default=False,
        ),
    ]
